config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
  registrations: "users/registrations"
}
  
  resources :tweets do
    collection do
      post :confirm
    end
  end  
  
  root 'top#index'
  
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
    # 名前は必須入力かつ20文字以内
    validates :name , length: {  maximum: 20 } , presence: true
    # 年齢は必須入力かつ数字以外入力できない、0歳以上
    validates :age , numericality:true, numericality: {  greater_than_or_equal_to: 0 } , presence: true
    # 内容は必須入力かつ2文字以上30文字以下
    validates :body , length: {minimum: 2 , maximum: 30 } , presence: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :content, presence: true
  validates :content, length: { in: 1..255 }  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :tweets
  mount_uploader :avatar, AvatarUploader
  validates :profile, length: { maximum: 300 }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_actionでdeviseのストロングパラメーターにnameカラムを追加するメソッドを実行します。
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache backimg profile)

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up).push(PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.for(:sign_in).push(PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.for(:account_update).push(PERMISSIBLE_ATTRIBUTES)
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end

  def edit
  end
  
  def update
    @blog.update(blogs_params)
    redirect_to blogs_path, notice: "ブログを更新しました！"
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end
  
  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end

    # idをキーとして値を取得するメソッド
    def set_blog
      @blog = Blog.find(params[:id])
    end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  def index
    # Messageを全て取得する。
    @messages = Message.all
    @message = Message.new
  end
  
  ## ここから追記
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

  private
  def message_params
    params.require(:message).permit(:name, :age, :body)
  end
  ## ここまで
  
    def set_message
    @message = Message.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all.order("updated_at DESC")
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
    @tweet = Tweet.new(tweets_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      # 一覧画面へ遷移して"ツイートしました！"とメッセージを表示します。
      redirect_to tweets_path, notice: "ツイートを作成しました！"
      NoticeMailer.sendmail_blog(@tweet).deliver
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end

  def edit
  end
  
  def update
    @tweet.update(tweets_params)
    if @tweet.valid?
      redirect_to tweets_path, notice: "ツイートを更新しました！"
    else
      render action:'edit'
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "ツイートを削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end

    # idをキーとして値を取得するメソッド
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
    
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

def destroy
  @tweets = Tweet.all
  @tweets.each do |tweet|
    if tweet.user_id == current_user.id
      tweet.delete
    end
  end
  super
end

end

app/helpers/application_helper.rb
module ApplicationHelper
 
 def profile_img_mn(user)
    if user_signed_in?
      if user.avatar?
        img_url = user.avatar.thumb_mn.url
      else
        img_url="/assets/sample-64x64.png"
      end
      image_tag(img_url, alt: user.name, width: "33", height: "33")
    else
      "dropdown"
    end
  end
  
 def profile_img_sm(user)
    if user_signed_in?
      if user.avatar?
        img_url = user.avatar.thumb_sm.url
      else
        img_url="/assets/sample-64x64.png"
      end
      image_tag(img_url, alt: user.name)
    end
  end
  
 def profile_img_bg(user)
    if user_signed_in?
      if user.avatar?
        img_url = user.avatar.thumb_bg.url
      else
        img_url="/assets/sample-64x64.png"
      end
      image_tag(img_url, alt: user.name)
    end
  end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :タイトル %>
<%= f.text_field :title, class: 'form-control' %>
<br>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ブログ一覧</h1>
      <%= link_to "ブログを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li>
        <%= link_to "ホーム", root_path, class: "glyphicon glyphicon-home" %></li>
      <li>
        <%= link_to "通知", tweets_path, class: "glyphicon glyphicon-bell" %></li>
      <li>
        <%= link_to "メッセージ", tweets_path, class: "glyphicon glyphicon-send" %></li>
      <li>
        <a href="<%= tweets_path %>">
        <img src="<%= asset_path "twitter_icon_dammy.png" %>">ツイート一覧</a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= profile_img_mn(current_user) %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
        <li>
        <a href="<%= new_tweet_path %>"><img src="<%= asset_path "tweet_pen.png" %>"></a>
      </ul>
      
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="キーワード検索">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <div id="twitter_bird">
        <img src="<%= asset_path "twitter_icon.png" %>">
      </div>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

</header>

  <%= yield %>

<footer>
  <p>運営会社タイムシフト株式会社</p><p>© 2015-2016 Copyright TimeShift Corp.</p>
</footer>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

  名前:
  <%= f.text_field :name %>
<br />
<br />
  年齢:
  <%= f.text_field :age %>
<br />
<br />
  内容:
  <%= f.text_area :body, :size => "100x2" %>
<br />
<br />
  <%= f.submit class: "btn btn-sm btn-primary" %>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>
    
  <div class="panel-body">
    <% @messages.each do |message| %>
      <span class="label label-info"><%= message.name %></span>
      <%= message.age %>
      <%= message.body %>
      (<%= link_to "edit" , edit_message_path(message) %>
         <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
        )

      <br>
    <% end %>
  </div>
</div>

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>

app/views/top/index.html.erb
  <section class="main-header">
    <p class="flash"><%= notice %><%= alert %></p>
    <img src="<%= asset_path "top.png" %>">
  </section>
  
  <section class="about">
    <h1>About Achieve</h1>
    <p>
       Achieveは、受講生のために作成された、教材用アプリです。<br>
       Achieveを作り終えることで、SecondTeamに参加するための力を身につけることができます。
    </p>
    <p>
       Acheiveを一言で表すと、タスク管理アプリです。<br>
       チームメンバーが、今どのようなタスクを行っているかリアルタイム
    </p>
  </section>

  <section class="function container-fluid">
    <div class="row">
    <h1>Function</h1>
      <div class="function-images">
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "key.png" %>">
            <p>ログイン機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "mails.png" %>">
            <p>メール送信機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "girls.png" %>">
            <p>友達つながり機能</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "comment.png" %>">
            <p>コメント投稿機能</p>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ツイート一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@tweet) do |f| %>
      <%= f.hidden_field :content %>
      <p>本文:<%= @tweet.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

<div class="container">
  
  <div id="container_top">
  </div>
  
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    
    <div id="container1">
       <%= profile_img_bg(current_user) %>
       <p><em><%= link_to current_user.name, edit_user_registration_path %></em></p>
       <p><%= current_user.profile %></p>
    </div>

    <div id="container2">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><%= link_to "ツイート", tweets_path %></li>
        <li role="presentation"><%= link_to "ツイートと返信", root_path %></li>
      </ul>
    
        <% @tweets.each do |tweet| %>
        
        <div class="row">
          <h4><%= tweet.content %></h4>
          
          <% if tweet.user_id == current_user.id %>
            <div>
              <p><em>投稿者:<%= link_to tweet.user.name, edit_user_registration_path %></em></p>
              <%= profile_img_sm(tweet.user) %>
              <p id="tw_date">作成日:<%= l tweet.created_at, format: :dt_default %>　更新日:<%= l tweet.updated_at, format: :dt_default %></p>
            </div>
              <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
              <%= link_to "削除", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
          <% else %>
            <div>
              <p><em>投稿者:<%= tweet.user.name if tweet.user.name.present? %></em></p>
              <%= profile_img_sm(tweet.user) %>
              <p id="tw_date">作成日:<%= l tweet.created_at, format: :dt_default %>　更新日:<%= l tweet.updated_at, format: :dt_default %></p>
            </div>
          <% end %>          
          
        </div>
        <% end %>
    </div>
    
  </div> 
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートする</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
</div>